apiVersion: v1
kind: List
items:
  # - apiVersion: v1
  #   kind: Service
  #   metadata:
  #     labels:
  #       app: spring-cloud-kubernetes-configuration-watcher
  #     name: spring-cloud-kubernetes-configuration-watcher
  #   spec:
  #     ports:
  #       - name: http
  #         port: 8888
  #         targetPort: 8888
  #     selector:
  #       app: spring-cloud-kubernetes-configuration-watcher
  #     type: ClusterIP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-configuration-watcher-deployment
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-configuration-watcher
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-configuration-watcher
        spec:
          serviceAccount: spring-cloud-kubernetes-configuration-watcher
          containers:
          - name: spring-cloud-kubernetes-configuration-watcher
            image: springcloud/spring-cloud-kubernetes-configuration-watcher:2.0.1-SNAPSHOT
            imagePullPolicy: IfNotPresent
            readinessProbe:
              httpGet:
                port: 8888
                path: /actuator/health/readiness
            livenessProbe:
              httpGet:
                port: 8888
                path: /actuator/health/liveness
            ports:
            - containerPort: 8888
            env:
            - name: logging.level.org.springframework.cloud.kubernetes
              value: "DEBUG"
            - name: TZ
              value: "Asia/Shanghai"