apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-service
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.properties: |-
    bean.message=Hello World! updated 865
    logging.level.org.springframework.cloud.kubernetes=DEBUG
    management.server.port=8080
    management.endpoints.web.exposure.include=*
    management.endpoints.web.tags.application=${spring.application.name}
